# Generated by Django 5.2.7 on 2025-10-12 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('goal', 'Goal Input'), ('commitment', 'Commitment Input'), ('summary', 'Summary Request'), ('other', 'Other')], default='other', max_length=32)),
                ('text', models.TextField(help_text='Raw natural language prompt from user or system')),
                ('llm_response', models.JSONField(blank=True, help_text='Structured JSON returned by LLM', null=True)),
                ('hash', models.CharField(help_text='sha256(or similar) of type+text', max_length=128, unique=True)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_mock', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
