# Generated by Django 5.2.7 on 2025-10-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commitment_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='user',
        ),
        migrations.DeleteModel(
            name='Commitment',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
