# Generated by Django 5.2.7 on 2025-10-14 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_goal_user_delete_commitment_delete_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='is_mock',
            new_name='is_refined',
        ),
    ]
