# Generated by Django 5.2.7 on 2025-10-14 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_is_mock_prompt_is_refined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('goal', 'Goal Input'), ('commitment', 'Commitment Input'), ('summary', 'Summary Request'), ('onboarding', 'Onboarding'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
