# Generated by Django 5.2.7 on 2025-10-15 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_prompt_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='type',
            field=models.CharField(choices=[('goal', 'Goal Input'), ('commitment', 'Commitment Input'), ('summary', 'Summary Request'), ('onboarding', 'Onboarding'), ('override', 'Override'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
