# Generated by Django 5.2.7 on 2025-10-13 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_duration_minutes', models.PositiveIntegerField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('related_goal', models.CharField(blank=True, max_length=255, null=True)),
                ('suggested_time', models.TimeField(blank=True, null=True)),
                ('is_flexible', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-priority', 'estimated_duration_minutes'],
            },
        ),
        migrations.CreateModel(
            name='DailySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_of_week', models.CharField(max_length=20)),
                ('total_committed_hours', models.FloatField()),
                ('total_available_hours', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('tasks', models.ManyToManyField(related_name='daily_schedules', to='llm.task')),
            ],
            options={
                'verbose_name': 'Daily Schedule',
                'verbose_name_plural': 'Daily Schedules',
                'ordering': ['date'],
            },
        ),
    ]
