# Generated by Django 5.2.7 on 2025-10-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Highest', 'Highest'), ('Urgent', 'Urgent'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
    ]
