# Generated by Django 5.2.7 on 2025-10-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0002_alter_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyschedule',
            name='pattern',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='updated_commitments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='updated_goals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Highest', 'Highest'), ('High', 'High'), ('Urgent', 'Urgent'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10),
        ),
    ]
