# Generated by Django 5.2.7 on 2025-10-13 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0003_dailyschedule_pattern_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyschedule',
            name='pattern',
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='dailyschedule',
            name='user_behaviour_patterns',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='total_available_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='dailyschedule',
            name='total_committed_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='is_flexible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Highest', 'Highest'), ('High', 'High'), ('Urgent', 'Urgent'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50),
        ),
    ]
