# Generated by Django 5.2.7 on 2025-10-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0004_remove_dailyschedule_pattern_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyschedule',
            old_name='updated_commitments',
            new_name='cleaned_commitments',
        ),
    ]
