# Generated by Django 5.2.7 on 2025-10-14 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0006_dailyschedule_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyschedule',
            old_name='cleaned_commitments',
            new_name='updated_commitment',
        ),
    ]
