# Generated by Django 5.2.7 on 2025-10-14 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0007_rename_cleaned_commitments_dailyschedule_updated_commitment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyschedule',
            old_name='updated_commitment',
            new_name='updated_commitments',
        ),
    ]
